---
- name: Configuración SNMP completa y habilitada en MikroTik
  hosts: all
  gather_facts: no

  vars:
    snmp_community: "OpenTI-Pub"
    snmp_addresses: "10.0.0.0/8"
    snmp_contact: "sitemaster@openti.mx"
    snmp_location: "SJI"
    snmp_trap_version: 1
    snmp_trap_generators: "temp-exception"

  tasks:
    - name: Habilitar SNMP globalmente
      ansible.netcommon.cli_command:
        command: "/snmp set enabled=yes"

    - name: Crear comunidad SNMP (habilitada)
      ansible.netcommon.cli_command:
        command: >
          /snmp community add name={{ snmp_community }}
          addresses={{ snmp_addresses }}
          read-access=yes disabled=no

    - name: Configurar contacto SNMP
      ansible.netcommon.cli_command:
        command: "/snmp set contact=\"{{ snmp_contact }}\""

    - name: Configurar ubicación SNMP
      ansible.netcommon.cli_command:
        command: "/snmp set location=\"{{ snmp_location }}\""

    - name: Configurar trap-community
      ansible.netcommon.cli_command:
        command: "/snmp set trap-community=\"{{ snmp_community }}\""

    - name: Configurar trap-version
      ansible.netcommon.cli_command:
        command: "/snmp set trap-version={{ snmp_trap_version }}"

    - name: Configurar trap-generators
      ansible.netcommon.cli_command:
        command: "/snmp set trap-generators={{ snmp_trap_generators }}"

    - name: Verificar SNMP habilitado
      ansible.netcommon.cli_command:
        command: "/snmp print"
      register: resultado_snmp

    - name: Verificar comunidades SNMP
      ansible.netcommon.cli_command:
        command: "/snmp community print"
      register: resultado_community

    - name: Mostrar resultado SNMP global en AWX
      debug:
        var: resultado_snmp.stdout_lines

    - name: Mostrar comunidades SNMP en AWX
      debug:
        var: resultado_community.stdout_lines

