---
- name: Configuraci贸n SNMP completa en MikroTik
  hosts: all
  gather_facts: no

  vars:
    snmp_community: "OpenTI-Pub"
    snmp_addresses: "10.0.0.0/8"
    snmp_contact: "sitemaster@openti.mx"
    snmp_location: "SJI"
    snmp_trap_version: 1
    snmp_trap_generators: "temp-exception"

  tasks:
    - name: Obtener versi贸n de RouterOS
      ansible.netcommon.cli_command:
        command: version
      register: version_out

    - name: Determinar prefijo de comandos SNMP
      set_fact:
        snmp_prefix: "{{ '/system/snmp' if 'v7.' in version_out.stdout else '/snmp' }}"

    - name: Habilitar SNMP (contexto correcto)
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set enabled=yes"

    - name: Agregar comunidad SNMP habilitada
      ansible.netcommon.cli_command:
        command: >
          /snmp community add name={{ snmp_community }} addresses={{ snmp_addresses }}
          read-access=yes disabled=no

    - name: Configurar contacto
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set contact=\"{{ snmp_contact }}\""

    - name: Configurar ubicaci贸n
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set location=\"{{ snmp_location }}\""

    - name: Configurar trap-community
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set trap-community=\"{{ snmp_community }}\""

    - name: Configurar trap-version
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set trap-version={{ snmp_trap_version }}"

    - name: Configurar trap-generators
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} set trap-generators={{ snmp_trap_generators }}"

    - name: Verificar estado SNMP
      ansible.netcommon.cli_command:
        command: "{{ snmp_prefix }} print"
      register: resultado_snmp

    - name: Verificar comunidades
      ansible.netcommon.cli_command:
        command: /snmp community print
      register: resultado_community

    - name: Mostrar configuraci贸n SNMP en AWX
      debug:
        var: resultado_snmp.stdout_lines

    - name: Mostrar comunidades SNMP en AWX
      debug:
        var: resultado_community.stdout_lines

