---
- name: Configurar SNMP MikroTik igual que Winbox
  hosts: all
  gather_facts: no

  vars:
    snmp_contact: "sitemaster@openti.mx"
    snmp_location: "SJI"
    snmp_trap_community: "OpenTI-Pub"
    snmp_trap_version: "1"
    snmp_trap_generators: "temp-exception"
    snmp_trap_interfaces: ""
    snmp_src_address: "::"   
    snmp_engine_id: ""       

  tasks:
    - name: Habilitar SNMP global
      ansible.netcommon.cli_command:
        command: /snmp set enabled=yes

    - name: Configurar contacto SNMP
      ansible.netcommon.cli_command:
        command: /snmp set contact="{{ snmp_contact }}"

    - name: Configurar ubicación SNMP
      ansible.netcommon.cli_command:
        command: /snmp set location="{{ snmp_location }}"

    - name: Configurar Trap Community
      ansible.netcommon.cli_command:
        command: /snmp set trap-community="{{ snmp_trap_community }}"

    - name: Configurar Trap Version
      ansible.netcommon.cli_command:
        command: /snmp set trap-version={{ snmp_trap_version }}

    - name: Configurar Trap Generators
      ansible.netcommon.cli_command:
        command: /snmp set trap-generators={{ snmp_trap_generators }}

    - name: Configurar Trap Interfaces
      ansible.netcommon.cli_command:
        command: /snmp set trap-interfaces={{ snmp_trap_interfaces }}

    - name: Configurar Src Address
      ansible.netcommon.cli_command:
        command: /snmp set src-address={{ snmp_src_address }}

    - name: Configurar Engine ID (opcional)
      ansible.netcommon.cli_command:
        command: /snmp set engine-id="{{ snmp_engine_id }}"

    - name: Mostrar configuración SNMP
      ansible.netcommon.cli_command:
        command: /snmp print
      register: snmp_conf

    - name: Mostrar comunidades SNMP
      ansible.netcommon.cli_command:
        command: /snmp community print
      register: snmp_community_conf

    - name: Mostrar salida en AWX (SNMP)
      debug:
        var: snmp_conf.stdout_lines

    - name: Mostrar salida en AWX (community)
      debug:
        var: snmp_community_conf.stdout_lines

