---
- name: Obtener IPs y nombre de MikroTik
  hosts: all
  gather_facts: false
  collections:
    - community.routeros

  tasks:
    - name: Obtener todas las direcciones IP de interfaces (detalle)
      community.routeros.routeros_command:
        commands:
          - /ip/address/print detail
      register: ip_address_detail

    - name: Obtener nombre del router
      community.routeros.routeros_command:
        commands:
          - /system/identity/print
      register: router_name

    - name: Mostrar resultado IPs
      debug:
        msg: "{{ ip_address_detail.stdout }}"

    - name: Mostrar nombre de router
      debug:
        msg: "{{ router_name.stdout }}"
