---
- name: Test MikroTik connectivity and gather router info
  hosts: all
  gather_facts: no
  tasks:
    - name: Get MikroTik Router Identity
      ansible.builtin.raw: "/system identity print"
      register: router_identity

    - name: Display MikroTik Identity
      debug:
        msg: "{{ router_identity.stdout }}"

    - name: Get MikroTik IP Addresses
      ansible.builtin.raw: "/ip address print detail"
      register: ip_addresses

    - name: Display MikroTik IP Addresses
      debug:
        msg: "{{ ip_addresses.stdout }}"

