---
- name: Obtener direcciones IP (detalle) y nombre de cada MikroTik
  hosts: all           # ← Grupo de tu inventario
  gather_facts: false

  # Forzamos la conexión de red adecuada
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: community.routeros.routeros

  tasks:
    - name: Listar IPs con todo el detalle
      community.routeros.command:      # ← Módulo correcto
        commands: /ip/address/print detail
      register: ip_detail

    - name: Leer el nombre (identity) del router
      community.routeros.command:
        commands: /system/identity/print
      register: router_name

    - name: Mostrar IPs
      debug:
        var: ip_detail.stdout          # Salida completa (lista de strings)

    - name: Mostrar nombre del router
      debug:
        var: router_name.stdout
