---
- name: Probar conexión con MikroTik
  hosts: all
  gather_facts: no
  tasks:
    - name: Ejecutar comando en MikroTik
      ansible.netcommon.cli_command:
        command: /system resource print

