---
- name: Obtener informaci贸n de IPs y detalles de routers MikroTik
  hosts: all
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: Obtener informaci贸n del sistema MikroTik
      routeros_command:
        commands:
          - /system identity print
          - /ip address print detail
          - /system resource print
      register: mikrotik_info

    - name: Extraer y mostrar informaci贸n relevante
      block:
        - name: Mostrar informaci贸n del router
          debug:
            msg: |
              Inventario: {{ inventory_hostname }}
              Nombre del Router: {{ mikrotik_info.stdout[0] | regex_replace('name: ', '') | trim }}
              Direcciones IP:
              {% for ip in mikrotik_info.stdout[1].split('\n') %}
              {% if ip and not ip.startswith('Flags') and not ip.startswith('Columns') %}
                - {{ ip | regex_replace('\s+', ' ') }}
              {% endif %}
              {% endfor %}
              Recursos:
                {{ mikrotik_info.stdout[2] | regex_replace('\n', '\n    ') }}
      when: mikrotik_info is defined and mikrotik_info.stdout is defined
