---
- name: Backup y descarga de configuraciones MikroTik
  hosts: all
  gather_facts: no

  tasks:
    - name: Generar archivo de respaldo (.rsc) en el router
      community.routeros.command:
        commands:
          - /system backup save name={{ inventory_hostname }}_backup.rsc
      register: backup_result
      ignore_errors: yes

    - name: Descargar backup al servidor AWX
      community.routeros.fetch:
        src: "{{ inventory_hostname }}_backup.rsc"
        dest: "{{ playbook_dir }}/backups/"  # Ruta dentro del proyecto AWX
        flat: yes
      when: backup_result is not skipped
