---
- name: Crear respaldo de configuración en MikroTik
  hosts: all  # Todos los hosts del inventario
  gather_facts: no  # No recolectar información innecesaria

  tasks:
    - name: Generar archivo de respaldo (.rsc) en el router
      community.routeros.command:
        commands:
          - /system backup save name={{ inventory_hostname }}_backup_{{ ansible_date_time.date }}.rsc
      register: backup_result
      ignore_errors: yes  # Continúa aunque falle en algún dispositivo

    - name: Mostrar resultado del backup
      ansible.builtin.debug:
        var: backup_result
      when: backup_result is not skipped
