---
# Playbook: Crear respaldo en MikroTik y obtener enlace HTTP
# Requisitos en el router:
#   /ip service set www enabled=yes      # habilitar WebFig/HTTP
#   RouterOS v7.7 o superior (para descargar con /file/…?download=1)
#
# Resultado: tras ejecutar el playbook verás un mensaje como
#   Descarga el respaldo vía HTTP: http://192.168.160.104/file/192.168.160.104_backup.backup?download=1
# que puedes abrir en un navegador para obtener el archivo.

- name: Crear respaldo y mostrar enlace HTTP
  hosts: all
  gather_facts: no

  tasks:
    - name: Crear archivo de respaldo (.backup)
      community.routeros.command:
        commands:
          - /system backup save name={{ inventory_hostname }}_backup
      register: backup_result
      ignore_errors: yes

    - name: Mostrar enlace HTTP para descargar respaldo
      debug:
        msg: "Descarga el respaldo vía HTTP: http://{{ inventory_hostname }}/file/{{ inventory_hostname }}_backup.backup?download=1"
      when: backup_result is succeeded
