---
# Playbook: Crear respaldo y mostrar link de descarga directamente desde el MikroTik

- name: Crear respaldo y entregar enlace directo
  hosts: all
  gather_facts: no

  tasks:
    - name: Crear archivo de respaldo (.backup)
      community.routeros.command:
        commands:
          - /system backup save name={{ inventory_hostname }}_backup
      register: backup_result
      ignore_errors: yes

    - name: Mostrar enlace FTP para descargar respaldo
      debug:
        msg: "Descarga el respaldo desde: ftp://{{ inventory_hostname }}/{{ inventory_hostname }}_backup.backup"
      when: backup_result is succeeded

    # Opcional: exportar configuración en texto (.rsc) y mostrar enlace
    - name: Exportar configuración en texto (.rsc)
      community.routeros.command:
        commands:
          - /export show-sensitive file={{ inventory_hostname }}_config
      when: backup_result is succeeded

    - name: Mostrar enlace FTP para descargar .rsc
      debug:
        msg: "Descarga la configuración desde: ftp://{{ inventory_hostname }}/{{ inventory_hostname }}_config.rsc"
      when: backup_result is succeeded

