---
- name: Crear respaldo de configuración en MikroTik
  hosts: all
  gather_facts: no  # No se necesitan facts

  tasks:
    - name: Generar archivo de respaldo (.rsc) en el router
      community.routeros.command:
        commands:
          - /system backup save name={{ inventory_hostname }}_backup.rsc
      register: backup_result
      ignore_errors: yes
