---
- name: Respaldar configuración MikroTik y descargar desde AWX
  hosts: all
  gather_facts: no

  vars:
    backup_dir: "./respaldos_mikrotik"
    backup_filename: "backup_config.rsc"

  tasks:
    - name: Crear carpeta local para respaldos
      local_action: file
        path={{ backup_dir }}
        state=directory
        mode=0755

    - name: Generar respaldo en router MikroTik
      ansible.netcommon.cli_command:
        command: "/export file={{ backup_filename }}"

    - name: Esperar 10 segundos para asegurar creación del respaldo
      pause:
        seconds: 10

    - name: Descargar respaldo desde router MikroTik
      ansible.builtin.fetch:
        src: "{{ backup_filename }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.rsc"
        flat: yes

    - name: Eliminar respaldo del router MikroTik
      ansible.netcommon.cli_command:
        command: "/file remove {{ backup_filename }}"

    - name: Confirmar éxito del respaldo
      debug:
        msg: "Respaldo del router {{ inventory_hostname }} descargado correctamente en AWX."

