---
- name: Respaldar configuración de router MikroTik
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    backup_file: "mikrotik-backup-{{ inventory_hostname }}-{{ ansible_date_time.date }}.backup"

  tasks:
    - name: Crear backup en router MikroTik
      community.routeros.command:
        commands:
          - "/system backup save name={{ backup_file }} dont-encrypt=yes"

    - name: Descargar backup desde router MikroTik
      ansible.netcommon.net_get:
        src: "{{ backup_file }}"
        dest: "backups/{{ backup_file }}"
        protocol: scp

    - name: Eliminar backup del router MikroTik después de descarga
      community.routeros.command:
        commands:
          - "/file remove {{ backup_file }}"
