---
- name: Backup MikroTik Router Configuration
  hosts: all  # Define el host en tu inventario
  gather_facts: no
  vars:
    backup_dir: "/opt/mikrotik_backups"
    backup_name: "backup-{{ ansible_date_time.date }}"
  
  tasks:
    - name: Crear directorio de backups si no existe
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
  
    - name: Generar y descargar backup del MikroTik (vía SSH)
      community.routeros.command:
        commands:
          - /system backup save name={{ backup_name }}.backup
          - /export file={{ backup_name }}
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
  
    - name: Descargar archivo .backup al servidor AWX
      ansible.builtin.fetch:
        src: "{{ backup_name }}.backup"
        dest: "{{ backup_dir }}/"
        flat: yes  # Evita estructura de carpetas adicionales
      delegate_to: localhost
  
    - name: Descargar archivo .rsc (export) al servidor AWX
      ansible.builtin.fetch:
        src: "{{ backup_name }}.rsc"
        dest: "{{ backup_dir }}/"
        flat: yes
      delegate_to: localhost
  
    - name: Eliminar archivos temporales del router
      community.routeros.command:
        commands:
          - /file remove {{ backup_name }}.backup
          - /file remove {{ backup_name }}.rsc
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        host: "{{ ansible_host }}"
