---
- name: Respaldar configuración de routers MikroTik
  hosts: all
  gather_facts: no

  vars:
    backup_dir: "./respaldos_mikrotik"
    backup_filename: "backup_config.rsc"

  tasks:
    - name: Crear carpeta local para respaldos
      local_action: file
        path={{ backup_dir }}
        state=directory
        mode=0755

    - name: Generar archivo de respaldo (.rsc) en router en raíz
      ansible.netcommon.cli_command:
        command: "/export file={{ backup_filename }}"

    - name: Esperar que se genere el archivo correctamente
      pause:
        seconds: 5

    - name: Verificar existencia del respaldo en el router
      ansible.netcommon.cli_command:
        command: "/file print without-paging"
      register: files_on_router

    - name: Mostrar archivos existentes en router (para depuración)
      debug:
        var: files_on_router.stdout_lines

    - name: Descargar respaldo desde el router (con ruta absoluta)
      ansible.builtin.fetch:
        src: "{{ backup_filename }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.rsc"
        flat: yes

    - name: Eliminar archivo de respaldo del router
      ansible.netcommon.cli_command:
        command: "/file remove {{ backup_filename }}"

    - name: Confirmar respaldo exitoso
      debug:
        msg: "Respaldo del router {{ inventory_hostname }} almacenado correctamente."
