---
- name: Configurar syslog remoto solo para errores en MikroTik
  hosts: all
  gather_facts: no

  vars:
    syslog_server: "10.10.8.132"
    syslog_action_name: "errorSyslog"
    syslog_topics: "error"
    syslog_port: 514

  tasks:

    - name: Eliminar acción anterior si existe (para limpieza)
      ansible.netcommon.cli_command:
        command: >
          /system logging action remove [find name="{{ syslog_action_name }}"]
      ignore_errors: yes

    - name: Crear nueva acción para enviar logs a servidor syslog
      ansible.netcommon.cli_command:
        command: >
          /system logging action add name={{ syslog_action_name }} target=remote
          remote={{ syslog_server }} remote-port={{ syslog_port }} syslog-severity=auto
          syslog-facility=daemon bsd-syslog=no

    - name: Agregar regla para enviar solo errores al servidor syslog
      ansible.netcommon.cli_command:
        command: >
          /system logging add topics={{ syslog_topics }} action={{ syslog_action_name }}

    - name: Verificar acciones de logging configuradas
      ansible.netcommon.cli_command:
        command: /system logging action print
      register: logging_actions

    - name: Verificar reglas de logging configuradas
      ansible.netcommon.cli_command:
        command: /system logging print
      register: logging_rules

    - name: Mostrar acciones de logging en AWX
      debug:
        var: logging_actions.stdout_lines

    - name: Mostrar reglas de logging en AWX
      debug:
        var: logging_rules.stdout_lines

    - name: Generar entrada de log de prueba tipo error
      ansible.netcommon.cli_command:
        command: /log error "Mensaje de prueba para verificar syslog remoto"
